export interface QuickReason {
  label: string;
  text: string;
}

export const quickReasonsByCategory: Record<string, QuickReason[]> = {
  parking: [
    { label: 'Signage was unclear', text: 'The signage at the location was unclear and did not clearly communicate the restriction.' },
    { label: 'Valid permit displayed', text: 'A valid permit was displayed at the time.' },
    { label: 'Blue badge holder', text: 'I am a blue badge holder and relevant circumstances should be taken into account.' },
    { label: 'Machine / app payment issue', text: 'There was an issue with the payment machine or parking app at the time.' },
    { label: 'Incorrect vehicle details', text: 'The vehicle or PCN details appear to be incorrect.' },
    { label: 'Emergency situation', text: 'There was an emergency situation which affected the circumstances.' },
    { label: 'Loading / unloading', text: 'The vehicle was being used for loading or unloading.' },
    { label: 'Ticket issued unfairly', text: 'I believe the ticket was issued unfairly in the circumstances.' },
    { label: 'Short overstay', text: 'Any overstay was minimal and should be considered proportionately.' },
    { label: 'I was not the driver', text: 'I was not the driver at the relevant time.' },
    { label: 'Duplicate ticket issued', text: 'A duplicate ticket appears to have been issued.' },
    { label: 'PCN details are incorrect', text: 'The PCN contains incorrect or inconsistent details.' },
  ],
  refund: [
    { label: 'Item not received', text: 'The item was never received.' },
    { label: 'Item damaged', text: 'The item arrived damaged.' },
    { label: 'Faulty product', text: 'The product is faulty and not of satisfactory quality.' },
    { label: 'Service not provided properly', text: 'The service provided was not carried out properly.' },
    { label: 'Wrong item sent', text: 'The wrong item was supplied.' },
    { label: 'Order cancelled', text: 'The order was cancelled but I have not received the refund owed.' },
    { label: 'Refund delayed', text: 'The refund has been delayed unreasonably.' },
    { label: 'Company ignoring me', text: 'I have attempted to resolve this but the company has not responded properly.' },
    { label: 'Returned but no refund', text: 'The item was returned but no refund has been processed.' },
    { label: 'Misleading description', text: 'The item or service did not match the description given.' },
    { label: 'Charged incorrectly', text: 'I was charged incorrectly.' },
    { label: 'Duplicate payment', text: 'A duplicate payment appears to have been taken.' },
  ],
  landlord: [
    { label: 'Repairs not completed', text: 'Necessary repairs have not been completed within a reasonable time.' },
    { label: 'Damp / mould', text: 'There is a serious damp and/or mould issue at the property.' },
    { label: 'Heating / hot water issue', text: 'There is a problem with heating and/or hot water.' },
    { label: 'Unsafe conditions', text: 'The condition of the property raises safety concerns.' },
    { label: 'Pest issue', text: 'There is a pest infestation or recurring pest problem.' },
    { label: 'Leak / water damage', text: 'There is a leak and/or water damage affecting the property.' },
    { label: 'No response from landlord', text: 'The landlord or agent has failed to respond appropriately.' },
    { label: 'Deposit issue', text: 'There is an issue relating to the tenancy deposit.' },
    { label: 'Harassment / unlawful entry', text: 'I am concerned about harassment and/or unlawful entry.' },
    { label: 'Electrical issue', text: 'There is an electrical fault or safety concern.' },
    { label: 'Broken windows / doors', text: 'Windows and/or doors are broken or insecure.' },
    { label: 'Ongoing disrepair', text: 'There is ongoing disrepair affecting the property.' },
  ],
  utility: [
    { label: 'Incorrect bill', text: 'The bill appears to be incorrect.' },
    { label: 'Overcharged', text: 'I believe I have been overcharged.' },
    { label: 'Meter problem', text: 'There appears to be a meter issue affecting billing.' },
    { label: 'Poor customer service', text: 'Customer service has been poor and the matter has not been handled properly.' },
    { label: 'Service interruption', text: 'There has been a service interruption or supply problem.' },
    { label: 'Account error', text: 'There is an error on my account.' },
    { label: 'Payment issue', text: 'There has been a payment-related issue.' },
    { label: 'Refund owed', text: 'I believe I am owed a refund.' },
    { label: 'Direct debit issue', text: 'There is a problem with the direct debit arrangement.' },
    { label: 'Debt collection unfair', text: 'Debt collection action appears unfair or premature.' },
    { label: 'Complaint ignored', text: 'My complaint has not been handled properly or responded to.' },
    { label: 'Back billing issue', text: 'There appears to be a back billing issue.' },
  ],
  employer: [
    { label: 'Unpaid wages', text: 'There is an issue relating to unpaid wages.' },
    { label: 'Holiday pay issue', text: 'There is a problem relating to holiday pay.' },
    { label: 'Unfair treatment', text: 'I believe I have been treated unfairly.' },
    { label: 'Discrimination concern', text: 'I have concerns about discrimination.' },
    { label: 'Harassment / bullying', text: 'I have concerns about harassment and/or bullying.' },
    { label: 'Contract issue', text: 'There is an issue relating to my contract or agreed terms.' },
    { label: 'Dismissal concern', text: 'I have concerns about dismissal or the threat of dismissal.' },
    { label: 'Disciplinary unfairness', text: 'The disciplinary process appears unfair.' },
    { label: 'Unsafe workplace', text: 'I have concerns about workplace safety.' },
    { label: 'Sick pay issue', text: 'There is an issue relating to sick pay.' },
    { label: 'Hours changed unfairly', text: 'My hours or working pattern have been changed unfairly.' },
    { label: 'No response from HR', text: 'I have not received an appropriate response from HR or management.' },
  ],
  consumer: [
    { label: 'Faulty goods', text: 'The goods are faulty.' },
    { label: 'Not as described', text: 'The goods or service were not as described.' },
    { label: 'Service not reasonable care', text: 'The service was not carried out with reasonable care and skill.' },
    { label: 'Late delivery', text: 'Delivery was significantly delayed.' },
    { label: 'No refund given', text: 'A refund has not been provided when it should have been.' },
    { label: 'Trader refusing responsibility', text: 'The trader is refusing to take responsibility.' },
    { label: 'Poor quality', text: 'The goods or service are of poor quality.' },
    { label: 'Hidden charges', text: 'There were hidden or unexpected charges.' },
    { label: 'Cancellation issue', text: 'There is an issue relating to cancellation rights.' },
    { label: 'Warranty issue', text: 'There is a problem relating to the warranty or guarantee.' },
    { label: 'Misleading information', text: 'I was given misleading information before purchase.' },
    { label: 'Breach of rights', text: 'I believe my consumer rights have been breached.' },
  ],
};
